[package]
name = "advent_2020_day_18"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
advent_2020_common = { path = "../advent_2020_common" }